*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 14:35:54 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xf694a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xf694a0 pid: 5848 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 5848, cores: 1)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 15:08:53 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x15e04a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x15e04a0 pid: 5895 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 5895, cores: 1)
Internal Server Error: /cache/global/img/gs.gif
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/middleware/common.py", line 62, in process_request
    if self.should_redirect_with_slash(request):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/middleware/common.py", line 80, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/urls/base.py", line 158, in is_valid_path
    resolve(path, urlconf)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenv/axf/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./python1812AXF/urls.py", line 21, in <module>
    url('^axf/',include('axf.urls',namespace='axf')),
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenv/axf/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./axf/urls.py", line 3, in <module>
    from axf import views
  File "./axf/views.py", line 12, in <module>
    from axf.alipay import alipay
  File "./axf/alipay/__init__.py", line 138, in <module>
    return_url="http://47.92.149.204/axf/returnurl/"  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./axf/alipay/__init__.py", line 37, in __init__
    self.alipay_public_key = RSA.import_key(fp.read())
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 733, in import_key
    (der, marker, enc_flag) = PEM.decode(tostr(extern_key), passphrase)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/Crypto/IO/PEM.py", line 127, in decode
    raise ValueError("Not a valid PEM post boundary")
ValueError: Not a valid PEM post boundary
[pid: 5895|app: 0|req: 1/1] 80.82.70.187 () {32 vars in 414 bytes} [Thu Mar 14 15:38:14 2019] GET /cache/global/img/gs.gif => generated 159699 bytes in 314 msecs (HTTP/1.1 500) 1 headers in 63 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.virtualenv/axf/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./python1812AXF/urls.py", line 21, in <module>
    url('^axf/',include('axf.urls',namespace='axf')),
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/.virtualenv/axf/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./axf/urls.py", line 3, in <module>
    from axf import views
  File "./axf/views.py", line 12, in <module>
    from axf.alipay import alipay
  File "./axf/alipay/__init__.py", line 138, in <module>
    return_url="http://47.92.149.204/axf/returnurl/"  # 同步支付通知url,在这个页面可以展示给用户看，只有付款成功后才会跳转
  File "./axf/alipay/__init__.py", line 37, in __init__
    self.alipay_public_key = RSA.import_key(fp.read())
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 733, in import_key
    (der, marker, enc_flag) = PEM.decode(tostr(extern_key), passphrase)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/Crypto/IO/PEM.py", line 127, in decode
    raise ValueError("Not a valid PEM post boundary")
ValueError: Not a valid PEM post boundary
[pid: 5895|app: 0|req: 2/2] 94.74.136.235 () {42 vars in 661 bytes} [Thu Mar 14 15:39:46 2019] GET / => generated 144472 bytes in 190 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 16:08:30 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x20344a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20344a0 pid: 6003 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6003, cores: 1)
[pid: 6003|app: 0|req: 1/1] 113.88.14.120 () {40 vars in 657 bytes} [Thu Mar 14 16:08:55 2019] GET /axf => generated 0 bytes in 39 msecs (HTTP/1.1 301) 3 headers in 110 bytes (1 switches on core 0)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6003|app: 0|req: 2/2] 113.88.14.120 () {40 vars in 659 bytes} [Thu Mar 14 16:08:55 2019] GET /axf/ => generated 20072 bytes in 61 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 6003|app: 0|req: 3/3] 113.87.160.176 () {40 vars in 634 bytes} [Thu Mar 14 16:08:59 2019] GET /favicon.ico => generated 2073 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 6003|app: 0|req: 4/4] 113.87.160.176 () {42 vars in 721 bytes} [Thu Mar 14 16:09:03 2019] GET /axf/ => generated 20072 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6003|app: 0|req: 5/5] 113.87.160.176 () {42 vars in 741 bytes} [Thu Mar 14 16:09:09 2019] GET /axf/cart/ => generated 1755 bytes in 4 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6003|app: 0|req: 6/6] 113.88.14.120 () {42 vars in 745 bytes} [Thu Mar 14 16:09:11 2019] GET /axf/mine/ => generated 5585 bytes in 5 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6003|app: 0|req: 7/7] 113.88.14.120 () {42 vars in 747 bytes} [Thu Mar 14 16:09:14 2019] GET /axf/login/ => generated 1569 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 6003|app: 0|req: 8/8] 113.87.160.176 () {50 vars in 930 bytes} [Thu Mar 14 16:09:25 2019] POST /axf/login/ => generated 0 bytes in 19 msecs (HTTP/1.1 302) 6 headers in 277 bytes (1 switches on core 0)
[pid: 6003|app: 0|req: 9/9] 113.87.160.176 () {46 vars in 835 bytes} [Thu Mar 14 16:09:25 2019] GET /axf/mine/ => generated 5760 bytes in 10 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6003|app: 0|req: 10/10] 113.87.160.176 () {44 vars in 803 bytes} [Thu Mar 14 16:09:32 2019] GET /axf/cart/ => generated 9978 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
Internal Server Error: /axf/generateorder/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'python1812axf.axf_order' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 373, in generateorder
    order.save()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'python1812axf.axf_order' doesn't exist")
[pid: 6003|app: 0|req: 11/11] 113.87.160.176 () {44 vars in 821 bytes} [Thu Mar 14 16:09:35 2019] GET /axf/generateorder/ => generated 197477 bytes in 113 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 16:22:13 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x166e4a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x166e4a0 pid: 6337 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6337, cores: 1)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 16:22:36 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x78f4a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x78f4a0 pid: 6352 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6352, cores: 1)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6352|app: 0|req: 1/1] 113.88.14.120 () {44 vars in 747 bytes} [Thu Mar 14 16:22:56 2019] GET /axf/ => generated 20072 bytes in 115 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 2/2] 113.88.14.120 () {44 vars in 777 bytes} [Thu Mar 14 16:23:05 2019] GET /axf/ => generated 20072 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 3/3] 113.88.14.120 () {44 vars in 801 bytes} [Thu Mar 14 16:23:10 2019] GET /axf/market/ => generated 11001 bytes in 20 msecs (HTTP/1.1 200) 4 headers in 196 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 4/4] 113.88.14.120 () {42 vars in 747 bytes} [Thu Mar 14 16:23:11 2019] GET /axf/cart/ => generated 1755 bytes in 6 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 5/5] 113.88.14.120 () {42 vars in 745 bytes} [Thu Mar 14 16:23:13 2019] GET /axf/mine/ => generated 5585 bytes in 6 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 6/6] 113.88.14.120 () {42 vars in 747 bytes} [Thu Mar 14 16:23:17 2019] GET /axf/login/ => generated 1569 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 7/7] 113.88.14.120 () {50 vars in 929 bytes} [Thu Mar 14 16:23:27 2019] POST /axf/login/ => generated 0 bytes in 15 msecs (HTTP/1.1 302) 6 headers in 277 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 8/8] 113.88.14.120 () {46 vars in 834 bytes} [Thu Mar 14 16:23:27 2019] GET /axf/mine/ => generated 5760 bytes in 9 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 9/9] 113.88.14.120 () {44 vars in 802 bytes} [Thu Mar 14 16:23:37 2019] GET /axf/cart/ => generated 3143 bytes in 17 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
Internal Server Error: /axf/generateorder/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'python1812axf.axf_order' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 373, in generateorder
    order.save()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'python1812axf.axf_order' doesn't exist")
[pid: 6352|app: 0|req: 10/10] 113.88.14.120 () {44 vars in 820 bytes} [Thu Mar 14 16:23:39 2019] GET /axf/generateorder/ => generated 197477 bytes in 94 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 11/11] 113.88.14.120 () {42 vars in 736 bytes} [Thu Mar 14 16:26:46 2019] GET /axf/returnurl/ => generated 0 bytes in 1 msecs (HTTP/1.1 302) 4 headers in 132 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 12/12] 113.88.14.120 () {42 vars in 726 bytes} [Thu Mar 14 16:26:46 2019] GET /axf/mine/ => generated 5760 bytes in 9 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 13/13] 113.88.14.120 () {42 vars in 736 bytes} [Thu Mar 14 16:27:42 2019] GET /axf/returnurl/ => generated 0 bytes in 1 msecs (HTTP/1.1 302) 4 headers in 132 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 14/14] 113.88.14.120 () {42 vars in 726 bytes} [Thu Mar 14 16:27:42 2019] GET /axf/mine/ => generated 5760 bytes in 8 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 15/15] 113.88.14.120 () {42 vars in 742 bytes} [Thu Mar 14 16:28:28 2019] GET /axf/appnotifyurl/ => generated 18 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6352|app: 0|req: 16/16] 113.88.14.120 () {44 vars in 773 bytes} [Thu Mar 14 16:29:43 2019] GET /axf/appnotifyurl/ => generated 18 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
Not Found: /
[pid: 6352|app: 0|req: 17/17] 60.191.38.77 () {34 vars in 435 bytes} [Thu Mar 14 16:42:29 2019] GET / => generated 2022 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 17:22:21 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xd824a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd824a0 pid: 6421 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6421, cores: 1)
[pid: 6421|app: 0|req: 1/1] 113.88.14.120 () {44 vars in 773 bytes} [Thu Mar 14 17:22:51 2019] GET /axf/appnotifyurl/ => generated 18 bytes in 37 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6421|app: 0|req: 2/2] 113.88.14.120 () {42 vars in 716 bytes} [Thu Mar 14 17:22:54 2019] GET /axf/ => generated 20072 bytes in 51 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 3/3] 113.88.14.120 () {44 vars in 777 bytes} [Thu Mar 14 17:22:58 2019] GET /axf/ => generated 20072 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 4/4] 113.87.160.176 () {44 vars in 798 bytes} [Thu Mar 14 17:25:05 2019] GET /axf/cart/ => generated 3143 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
Internal Server Error: /axf/generateorder/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'python1812axf.axf_order' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 373, in generateorder
    order.save()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'python1812axf.axf_order' doesn't exist")
[pid: 6421|app: 0|req: 5/5] 113.87.160.176 () {44 vars in 821 bytes} [Thu Mar 14 17:25:07 2019] GET /axf/generateorder/ => generated 197480 bytes in 95 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /axf/generateorder/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'python1812axf.axf_order' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 373, in generateorder
    order.save()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'python1812axf.axf_order' doesn't exist")
[pid: 6421|app: 0|req: 6/6] 113.87.160.176 () {44 vars in 791 bytes} [Thu Mar 14 17:25:27 2019] GET /axf/generateorder/ => generated 197449 bytes in 97 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6421|app: 0|req: 7/7] 113.88.14.120 () {42 vars in 716 bytes} [Thu Mar 14 17:28:15 2019] GET /axf/ => generated 20072 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 8/8] 113.88.14.120 () {44 vars in 777 bytes} [Thu Mar 14 17:28:19 2019] GET /axf/ => generated 20072 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 9/9] 113.88.14.120 () {44 vars in 797 bytes} [Thu Mar 14 17:28:22 2019] GET /axf/cart/ => generated 3143 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 10/10] 113.88.14.120 () {44 vars in 820 bytes} [Thu Mar 14 17:28:24 2019] GET /axf/generateorder/ => generated 1208 bytes in 29 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 11/11] 113.88.14.120 () {44 vars in 748 bytes} [Thu Mar 14 17:28:26 2019] GET /axf/pay/?orderid= => generated 47 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 12/12] 113.88.14.120 () {44 vars in 748 bytes} [Thu Mar 14 17:28:31 2019] GET /axf/pay/?orderid= => generated 47 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 13/13] 113.88.14.120 () {44 vars in 748 bytes} [Thu Mar 14 17:28:33 2019] GET /axf/pay/?orderid= => generated 47 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 14/14] 113.88.14.120 () {44 vars in 748 bytes} [Thu Mar 14 17:28:34 2019] GET /axf/pay/?orderid= => generated 47 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 15/15] 113.88.14.120 () {44 vars in 748 bytes} [Thu Mar 14 17:28:35 2019] GET /axf/pay/?orderid= => generated 47 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 16/16] 113.88.14.120 () {44 vars in 748 bytes} [Thu Mar 14 17:28:36 2019] GET /axf/pay/?orderid= => generated 47 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 17/17] 113.88.14.120 () {44 vars in 748 bytes} [Thu Mar 14 17:28:37 2019] GET /axf/pay/?orderid= => generated 47 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6421|app: 0|req: 18/18] 113.88.14.120 () {44 vars in 748 bytes} [Thu Mar 14 17:28:37 2019] GET /axf/pay/?orderid= => generated 47 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 17:38:38 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1e454a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1e454a0 pid: 6494 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6494, cores: 1)
[pid: 6494|app: 0|req: 1/1] 113.87.160.176 () {44 vars in 806 bytes} [Thu Mar 14 17:38:56 2019] GET /axf/generateorder/ => generated 1063 bytes in 240 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
Internal Server Error: /axf/pay/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 428, in pay
    order = Order.objects.get(pk=orderid)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[pid: 6494|app: 0|req: 2/2] 113.87.160.176 () {44 vars in 749 bytes} [Thu Mar 14 17:39:00 2019] GET /axf/pay/?orderid= => generated 13656 bytes in 50 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 6494|app: 0|req: 3/3] 113.87.160.176 () {44 vars in 806 bytes} [Thu Mar 14 17:39:07 2019] GET /axf/generateorder/ => generated 1063 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
Internal Server Error: /axf/pay/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 428, in pay
    order = Order.objects.get(pk=orderid)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[pid: 6494|app: 0|req: 4/4] 113.87.160.176 () {44 vars in 749 bytes} [Thu Mar 14 17:39:09 2019] GET /axf/pay/?orderid= => generated 13656 bytes in 23 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /axf/pay/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 428, in pay
    order = Order.objects.get(pk=orderid)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[pid: 6494|app: 0|req: 5/5] 113.87.160.176 () {44 vars in 749 bytes} [Thu Mar 14 17:39:11 2019] GET /axf/pay/?orderid= => generated 13656 bytes in 23 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /axf/pay/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 428, in pay
    order = Order.objects.get(pk=orderid)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[pid: 6494|app: 0|req: 6/6] 113.87.160.176 () {44 vars in 749 bytes} [Thu Mar 14 17:39:12 2019] GET /axf/pay/?orderid= => generated 13656 bytes in 23 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6494|app: 0|req: 7/7] 113.87.160.176 () {42 vars in 717 bytes} [Thu Mar 14 17:39:37 2019] GET /axf/ => generated 20072 bytes in 28 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6494|app: 0|req: 8/8] 113.87.160.176 () {44 vars in 802 bytes} [Thu Mar 14 17:39:40 2019] GET /axf/market/ => generated 11001 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 9/9] 113.87.160.176 () {44 vars in 756 bytes} [Thu Mar 14 17:39:42 2019] GET /axf/addcart/?goodsid=497 => generated 118 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 10/10] 113.87.160.176 () {44 vars in 756 bytes} [Thu Mar 14 17:39:43 2019] GET /axf/addcart/?goodsid=496 => generated 151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 11/11] 113.87.160.176 () {44 vars in 756 bytes} [Thu Mar 14 17:39:45 2019] GET /axf/addcart/?goodsid=495 => generated 113 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6494|app: 0|req: 12/12] 113.87.160.176 () {44 vars in 805 bytes} [Thu Mar 14 17:39:46 2019] GET /axf/cart/ => generated 4874 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6494|app: 0|req: 13/13] 113.87.160.176 () {44 vars in 807 bytes} [Thu Mar 14 17:39:51 2019] GET /axf/market/ => generated 11973 bytes in 23 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
[pid: 6494|app: 0|req: 14/14] 113.87.160.176 () {44 vars in 818 bytes} [Thu Mar 14 17:39:53 2019] GET /axf/market/ => generated 90163 bytes in 36 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 15/15] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:39:55 2019] GET /axf/addcart/?goodsid=554 => generated 151 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 16/16] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:39:56 2019] GET /axf/addcart/?goodsid=555 => generated 118 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 17/17] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:39:57 2019] GET /axf/addcart/?goodsid=556 => generated 142 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 18/18] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:40:04 2019] GET /axf/addcart/?goodsid=557 => generated 132 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 19/19] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:40:05 2019] GET /axf/addcart/?goodsid=557 => generated 132 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 20/20] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:40:06 2019] GET /axf/addcart/?goodsid=557 => generated 132 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 21/21] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:40:07 2019] GET /axf/addcart/?goodsid=557 => generated 132 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6494|app: 0|req: 22/22] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:40:07 2019] GET /axf/addcart/?goodsid=557 => generated 132 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6494|app: 0|req: 23/23] 113.87.160.176 () {44 vars in 814 bytes} [Thu Mar 14 17:40:09 2019] GET /axf/cart/ => generated 8338 bytes in 22 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6494|app: 0|req: 24/24] 113.87.160.176 () {44 vars in 830 bytes} [Thu Mar 14 17:40:11 2019] GET /axf/generateorder/ => generated 2155 bytes in 90 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
Internal Server Error: /axf/pay/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 428, in pay
    order = Order.objects.get(pk=orderid)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[pid: 6494|app: 0|req: 25/25] 113.87.160.176 () {44 vars in 758 bytes} [Thu Mar 14 17:40:14 2019] GET /axf/pay/?orderid= => generated 13677 bytes in 25 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 17:43:35 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8f04a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8f04a0 pid: 6554 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6554, cores: 1)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6554|app: 0|req: 1/1] 113.87.160.176 () {42 vars in 726 bytes} [Thu Mar 14 17:43:52 2019] GET /axf/ => generated 20072 bytes in 267 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6554|app: 0|req: 2/2] 113.87.160.176 () {44 vars in 807 bytes} [Thu Mar 14 17:43:56 2019] GET /axf/cart/ => generated 2290 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6554|app: 0|req: 3/3] 113.87.160.176 () {44 vars in 816 bytes} [Thu Mar 14 17:44:59 2019] GET /axf/market/ => generated 78550 bytes in 28 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6554|app: 0|req: 4/4] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:45:01 2019] GET /axf/addcart/?goodsid=557 => generated 132 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6554|app: 0|req: 5/5] 113.87.160.176 () {44 vars in 814 bytes} [Thu Mar 14 17:45:02 2019] GET /axf/cart/ => generated 3153 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6554|app: 0|req: 6/6] 113.87.160.176 () {44 vars in 830 bytes} [Thu Mar 14 17:45:05 2019] GET /axf/generateorder/ => generated 1218 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
Internal Server Error: /axf/pay/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 428, in pay
    order = Order.objects.get(pk=orderid)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
[pid: 6554|app: 0|req: 7/7] 113.87.160.176 () {44 vars in 758 bytes} [Thu Mar 14 17:45:07 2019] GET /axf/pay/?orderid= => generated 13677 bytes in 26 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 17:55:55 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x194a4a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x194a4a0 pid: 6622 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6622, cores: 1)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6622|app: 0|req: 1/1] 113.87.160.176 () {42 vars in 726 bytes} [Thu Mar 14 17:56:11 2019] GET /axf/ => generated 20072 bytes in 259 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6622|app: 0|req: 2/2] 113.87.160.176 () {44 vars in 807 bytes} [Thu Mar 14 17:56:14 2019] GET /axf/cart/ => generated 2290 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6622|app: 0|req: 3/3] 113.87.160.176 () {44 vars in 816 bytes} [Thu Mar 14 17:56:16 2019] GET /axf/market/ => generated 78550 bytes in 32 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6622|app: 0|req: 4/4] 113.87.160.176 () {44 vars in 765 bytes} [Thu Mar 14 17:56:18 2019] GET /axf/addcart/?goodsid=557 => generated 132 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6622|app: 0|req: 5/5] 113.87.160.176 () {44 vars in 814 bytes} [Thu Mar 14 17:56:20 2019] GET /axf/cart/ => generated 3154 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6622|app: 0|req: 6/6] 113.87.160.176 () {44 vars in 830 bytes} [Thu Mar 14 17:56:29 2019] GET /axf/generateorder/ => generated 1219 bytes in 31 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6622|app: 0|req: 7/7] 113.87.160.176 () {44 vars in 760 bytes} [Thu Mar 14 17:56:31 2019] GET /axf/pay/?orderid=6 => generated 1004 bytes in 28 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 18:05:03 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x214e4a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x214e4a0 pid: 6687 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6687, cores: 1)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6687|app: 0|req: 1/1] 113.88.14.120 () {42 vars in 755 bytes} [Thu Mar 14 18:05:19 2019] GET /axf/ => generated 20072 bytes in 267 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 2/2] 113.88.14.120 () {44 vars in 810 bytes} [Thu Mar 14 18:05:21 2019] GET /axf/market/ => generated 78550 bytes in 32 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6687|app: 0|req: 3/3] 113.88.14.120 () {44 vars in 764 bytes} [Thu Mar 14 18:05:24 2019] GET /axf/addcart/?goodsid=557 => generated 132 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6687|app: 0|req: 4/4] 113.88.14.120 () {44 vars in 764 bytes} [Thu Mar 14 18:05:25 2019] GET /axf/addcart/?goodsid=558 => generated 150 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 5/5] 113.88.14.120 () {44 vars in 813 bytes} [Thu Mar 14 18:05:27 2019] GET /axf/cart/ => generated 4027 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
12
[pid: 6687|app: 0|req: 6/6] 113.88.14.120 () {44 vars in 778 bytes} [Thu Mar 14 18:05:29 2019] GET /axf/changecarrtselect/?cartid=12 => generated 79 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 7/7] 113.88.14.120 () {44 vars in 829 bytes} [Thu Mar 14 18:05:31 2019] GET /axf/generateorder/ => generated 1219 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 8/8] 113.88.14.120 () {44 vars in 759 bytes} [Thu Mar 14 18:05:34 2019] GET /axf/pay/?orderid=7 => generated 1000 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 9/9] 203.209.240.124 () {34 vars in 503 bytes} [Thu Mar 14 18:16:14 2019] POST /axf/appnotifyurl/ => generated 18 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 10/10] 113.88.14.120 () {44 vars in 2293 bytes} [Thu Mar 14 18:16:29 2019] GET /axf/returnurl/?charset=utf-8&out_trade_no=405491829507456843&method=alipay.trade.page.pay.return&total_amount=8.90&sign=gAq9YRBJPQeXvhChUNnx02t1Rg71LUohdXis6Oat%2FhejUDpO3dBm98pv1Ob15AZcZcxGz3VrBUWZRVb1g03ur%2Bwjpgx%2BdjoiuMb9jyH7hUKV0edIxXQCMQNwy930guHxCRxsyxkV%2FnluaERMNoHZwXgFUi6GhMP%2B%2FEOii2wDP9QPQ4gjCRDJy4LR%2BIeJHpMVUsc09VSII%2BvgC9jJEgm5PLmwE0Y%2BFALpbLV%2F36oQHesXkAqQ488FRCYEEufbYwLLPPKYwr3Q%2BM5%2BXQc8WDk8%2FVnQBQIHOxqq1cAQa7%2FDrSFoYveJuAlgT6qPwAaoozCAzJNQUp54IEopSbJ%2FSdXL%2Bw%3D%3D&trade_no=2019031422001443700501241623&auth_app_id=2016092300574253&version=1.0&app_id=2016092300574253&sign_type=RSA2&seller_id=2088102176844131&timestamp=2019-03-14+18%3A16%3A20 => generated 0 bytes in 1 msecs (HTTP/1.1 302) 4 headers in 132 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 11/11] 113.88.14.120 () {44 vars in 954 bytes} [Thu Mar 14 18:16:29 2019] GET /axf/mine/ => generated 5760 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 12/12] 183.40.39.236 () {40 vars in 819 bytes} [Thu Mar 14 18:17:03 2019] GET /axf => generated 0 bytes in 0 msecs (HTTP/1.1 301) 3 headers in 110 bytes (1 switches on core 0)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6687|app: 0|req: 13/13] 183.40.39.236 () {40 vars in 821 bytes} [Thu Mar 14 18:17:03 2019] GET /axf/ => generated 20072 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 6687|app: 0|req: 14/14] 183.40.39.236 () {42 vars in 819 bytes} [Thu Mar 14 18:17:06 2019] GET /favicon.ico => generated 2073 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 15/15] 113.88.14.120 () {46 vars in 1015 bytes} [Thu Mar 14 18:17:13 2019] GET /axf/mine/ => generated 5760 bytes in 8 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 16/16] 183.40.39.236 () {42 vars in 876 bytes} [Thu Mar 14 18:17:22 2019] GET /axf/market/ => generated 294144 bytes in 65 msecs (HTTP/1.1 200) 4 headers in 197 bytes (1 switches on core 0)
None 1111111111
-1
[pid: 6687|app: 0|req: 17/17] 183.40.39.236 () {44 vars in 785 bytes} [Thu Mar 14 18:17:27 2019] GET /axf/addcart/?goodsid=74 => generated 61 bytes in 3 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 18/18] 183.40.39.236 () {42 vars in 837 bytes} [Thu Mar 14 18:17:27 2019] GET /axf/login/ => generated 1569 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 19/19] 183.40.39.236 () {50 vars in 1017 bytes} [Thu Mar 14 18:17:42 2019] POST /axf/login/ => generated 0 bytes in 14 msecs (HTTP/1.1 302) 6 headers in 277 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 20/20] 183.40.39.236 () {44 vars in 909 bytes} [Thu Mar 14 18:17:42 2019] GET /axf/mine/ => generated 5760 bytes in 9 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 21/21] 183.40.39.236 () {42 vars in 881 bytes} [Thu Mar 14 18:17:47 2019] GET /axf/market/ => generated 310102 bytes in 74 msecs (HTTP/1.1 200) 4 headers in 126 bytes (1 switches on core 0)
7c315f4a83e0de3aab3ae40735ef9de8 1111111111
1 22222222
[pid: 6687|app: 0|req: 22/22] 183.40.39.236 () {44 vars in 829 bytes} [Thu Mar 14 18:17:52 2019] GET /axf/addcart/?goodsid=74 => generated 133 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
7c315f4a83e0de3aab3ae40735ef9de8 1111111111
1 22222222
[pid: 6687|app: 0|req: 23/23] 183.40.39.236 () {44 vars in 829 bytes} [Thu Mar 14 18:17:53 2019] GET /axf/addcart/?goodsid=75 => generated 133 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
7c315f4a83e0de3aab3ae40735ef9de8 1111111111
1 22222222
[pid: 6687|app: 0|req: 24/24] 183.40.39.236 () {44 vars in 829 bytes} [Thu Mar 14 18:17:53 2019] GET /axf/addcart/?goodsid=75 => generated 133 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 25/25] 183.40.39.236 () {42 vars in 879 bytes} [Thu Mar 14 18:17:55 2019] GET /axf/cart/ => generated 4862 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 26/26] 183.40.39.236 () {44 vars in 841 bytes} [Thu Mar 14 18:17:58 2019] GET /axf/changecartall/?status=true => generated 78 bytes in 18 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 27/27] 183.40.39.236 () {42 vars in 895 bytes} [Thu Mar 14 18:17:59 2019] GET /axf/generateorder/ => generated 1540 bytes in 49 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 28/28] 183.40.39.236 () {44 vars in 826 bytes} [Thu Mar 14 18:18:03 2019] GET /axf/pay/?orderid=8 => generated 1009 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 29/29] 113.88.14.120 () {44 vars in 2323 bytes} [Thu Mar 14 18:18:53 2019] GET /axf/returnurl/?charset=utf-8&out_trade_no=405491829507456843&method=alipay.trade.page.pay.return&total_amount=8.90&sign=gAq9YRBJPQeXvhChUNnx02t1Rg71LUohdXis6Oat%2FhejUDpO3dBm98pv1Ob15AZcZcxGz3VrBUWZRVb1g03ur%2Bwjpgx%2BdjoiuMb9jyH7hUKV0edIxXQCMQNwy930guHxCRxsyxkV%2FnluaERMNoHZwXgFUi6GhMP%2B%2FEOii2wDP9QPQ4gjCRDJy4LR%2BIeJHpMVUsc09VSII%2BvgC9jJEgm5PLmwE0Y%2BFALpbLV%2F36oQHesXkAqQ488FRCYEEufbYwLLPPKYwr3Q%2BM5%2BXQc8WDk8%2FVnQBQIHOxqq1cAQa7%2FDrSFoYveJuAlgT6qPwAaoozCAzJNQUp54IEopSbJ%2FSdXL%2Bw%3D%3D&trade_no=2019031422001443700501241623&auth_app_id=2016092300574253&version=1.0&app_id=2016092300574253&sign_type=RSA2&seller_id=2088102176844131&timestamp=2019-03-14+18%3A16%3A20 => generated 0 bytes in 1 msecs (HTTP/1.1 302) 4 headers in 132 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 30/30] 113.88.14.120 () {44 vars in 984 bytes} [Thu Mar 14 18:18:53 2019] GET /axf/mine/ => generated 5760 bytes in 9 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 31/31] 61.151.207.141 () {36 vars in 603 bytes} [Thu Mar 14 18:18:55 2019] GET /axf/cart => generated 0 bytes in 0 msecs (HTTP/1.1 301) 3 headers in 115 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 32/32] 180.97.118.223 () {36 vars in 588 bytes} [Thu Mar 14 18:18:59 2019] GET /axf/generateorder => generated 0 bytes in 0 msecs (HTTP/1.1 301) 3 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 33/33] 140.205.118.205 () {34 vars in 503 bytes} [Thu Mar 14 18:21:11 2019] POST /axf/appnotifyurl/ => generated 18 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 100 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 34/34] 113.88.14.120 () {44 vars in 811 bytes} [Thu Mar 14 18:33:57 2019] GET /axf/cart/ => generated 2290 bytes in 10 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 35/35] 113.88.14.120 () {44 vars in 815 bytes} [Thu Mar 14 18:33:58 2019] GET /axf/market/ => generated 78550 bytes in 29 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 36/36] 113.88.14.120 () {44 vars in 818 bytes} [Thu Mar 14 18:34:01 2019] GET /axf/market/ => generated 53229 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6687|app: 0|req: 37/37] 113.88.14.120 () {44 vars in 765 bytes} [Thu Mar 14 18:34:03 2019] GET /axf/addcart/?goodsid=500 => generated 129 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 38/38] 113.88.14.120 () {44 vars in 814 bytes} [Thu Mar 14 18:34:05 2019] GET /axf/cart/ => generated 3151 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 39/39] 113.88.14.120 () {44 vars in 830 bytes} [Thu Mar 14 18:34:07 2019] GET /axf/generateorder/ => generated 1216 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6687|app: 0|req: 40/40] 113.88.14.120 () {44 vars in 760 bytes} [Thu Mar 14 18:34:08 2019] GET /axf/pay/?orderid=9 => generated 1010 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 6687|app: 0|req: 41/41] 39.107.114.182 () {34 vars in 461 bytes} [Thu Mar 14 18:55:47 2019] GET / => generated 2022 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 19:09:15 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x23794a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x23794a0 pid: 6816 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6816, cores: 1)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6816|app: 0|req: 1/1] 113.87.160.176 () {42 vars in 727 bytes} [Thu Mar 14 19:10:36 2019] GET /axf/ => generated 20072 bytes in 263 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 6816|app: 0|req: 2/2] 113.87.160.176 () {42 vars in 701 bytes} [Thu Mar 14 19:10:38 2019] GET /favicon.ico => generated 2073 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 3/3] 113.87.160.176 () {44 vars in 788 bytes} [Thu Mar 14 19:10:47 2019] GET /axf/ => generated 20072 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 4/4] 113.87.160.176 () {44 vars in 788 bytes} [Thu Mar 14 19:10:51 2019] GET /axf/ => generated 20072 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 5/5] 113.87.160.176 () {44 vars in 788 bytes} [Thu Mar 14 19:10:57 2019] GET /axf/ => generated 20072 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 6/6] 113.87.160.176 () {44 vars in 812 bytes} [Thu Mar 14 19:11:02 2019] GET /axf/market/ => generated 53229 bytes in 26 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 7/7] 113.87.160.176 () {44 vars in 815 bytes} [Thu Mar 14 19:11:04 2019] GET /axf/mine/ => generated 6138 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 8/8] 113.87.160.176 () {44 vars in 813 bytes} [Thu Mar 14 19:11:09 2019] GET /axf/cart/ => generated 2290 bytes in 10 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 9/9] 113.87.160.176 () {44 vars in 813 bytes} [Thu Mar 14 19:11:11 2019] GET /axf/mine/ => generated 6138 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 10/10] 113.87.160.176 () {46 vars in 844 bytes} [Thu Mar 14 19:11:28 2019] GET /axf/mine/ => generated 6138 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 11/11] 113.87.160.176 () {46 vars in 844 bytes} [Thu Mar 14 19:11:29 2019] GET /axf/mine/ => generated 6138 bytes in 10 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 12/12] 113.87.160.176 () {46 vars in 844 bytes} [Thu Mar 14 19:11:30 2019] GET /axf/mine/ => generated 6138 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 13/13] 113.87.160.176 () {46 vars in 844 bytes} [Thu Mar 14 19:11:30 2019] GET /axf/mine/ => generated 6138 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 14/14] 113.87.160.176 () {46 vars in 844 bytes} [Thu Mar 14 19:11:31 2019] GET /axf/mine/ => generated 6138 bytes in 10 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 15/15] 113.87.160.176 () {46 vars in 844 bytes} [Thu Mar 14 19:11:31 2019] GET /axf/mine/ => generated 6138 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 16/16] 113.87.160.176 () {44 vars in 813 bytes} [Thu Mar 14 19:11:44 2019] GET /axf/cart/ => generated 2290 bytes in 10 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 17/17] 113.87.160.176 () {44 vars in 817 bytes} [Thu Mar 14 19:11:46 2019] GET /axf/market/ => generated 53229 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6816|app: 0|req: 18/18] 113.87.160.176 () {44 vars in 766 bytes} [Thu Mar 14 19:11:48 2019] GET /axf/addcart/?goodsid=501 => generated 129 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
b3aaf37c356dd83345a6f12bda636ffc 1111111111
1 22222222
[pid: 6816|app: 0|req: 19/19] 113.87.160.176 () {44 vars in 766 bytes} [Thu Mar 14 19:11:50 2019] GET /axf/addcart/?goodsid=501 => generated 129 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 20/20] 113.87.160.176 () {44 vars in 815 bytes} [Thu Mar 14 19:11:52 2019] GET /axf/cart/ => generated 3140 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 21/21] 113.87.160.176 () {44 vars in 831 bytes} [Thu Mar 14 19:11:54 2019] GET /axf/generateorder/ => generated 1217 bytes in 29 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 22/22] 113.87.160.176 () {44 vars in 763 bytes} [Thu Mar 14 19:11:57 2019] GET /axf/pay/?orderid=10 => generated 1004 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 23/23] 113.87.160.176 () {44 vars in 813 bytes} [Thu Mar 14 19:12:06 2019] GET /axf/mine/ => generated 6138 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 24/24] 113.87.160.176 () {44 vars in 821 bytes} [Thu Mar 14 19:12:07 2019] GET /axf/loginout/ => generated 6140 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 195 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 25/25] 113.87.160.176 () {44 vars in 777 bytes} [Thu Mar 14 19:12:09 2019] GET /axf/market/ => generated 53229 bytes in 20 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
None 1111111111
-1
[pid: 6816|app: 0|req: 26/26] 113.87.160.176 () {44 vars in 722 bytes} [Thu Mar 14 19:12:11 2019] GET /axf/addcart/?goodsid=500 => generated 61 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 27/27] 113.87.160.176 () {44 vars in 786 bytes} [Thu Mar 14 19:12:11 2019] GET /axf/login/ => generated 1569 bytes in 4 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Internal Server Error: /axf/login/
Traceback (most recent call last):
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenv/axf/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./axf/views.py", line 173, in login
    user = user.last()
AttributeError: 'User' object has no attribute 'last'
[pid: 6816|app: 0|req: 28/28] 113.87.160.176 () {52 vars in 966 bytes} [Thu Mar 14 19:12:24 2019] POST /axf/login/ => generated 60141 bytes in 42 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 29/29] 113.88.14.120 () {44 vars in 759 bytes} [Thu Mar 14 19:13:51 2019] GET /axf/market/ => generated 53229 bytes in 32 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
[pid: 6816|app: 0|req: 30/30] 113.88.14.120 () {44 vars in 744 bytes} [Thu Mar 14 19:13:55 2019] GET /axf/loginout/ => generated 6140 bytes in 7 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 14 19:17:38 2019] ***
compiled with version: 5.4.0 20160609 on 13 March 2019 14:08:22
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
nodename: Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /var/www/axf
writing pidfile to uwsgi.pid
detected binary path: /root/.virtualenv/axf/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/axf
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1801
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8030 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x13884a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x13884a0 pid: 6917 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 6917, cores: 1)
[pid: 6917|app: 0|req: 1/1] 113.87.160.176 () {44 vars in 745 bytes} [Thu Mar 14 19:17:45 2019] GET /axf/loginout/ => generated 6140 bytes in 223 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 2/2] 113.87.160.176 () {44 vars in 775 bytes} [Thu Mar 14 19:17:49 2019] GET /axf/loginout/ => generated 6140 bytes in 7 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 3/3] 113.87.160.176 () {44 vars in 790 bytes} [Thu Mar 14 19:17:52 2019] GET /axf/market/ => generated 53229 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
None 1111111111
-1
[pid: 6917|app: 0|req: 4/4] 113.87.160.176 () {44 vars in 735 bytes} [Thu Mar 14 19:17:53 2019] GET /axf/addcart/?goodsid=500 => generated 61 bytes in 1 msecs (HTTP/1.1 200) 4 headers in 114 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 5/5] 113.87.160.176 () {44 vars in 786 bytes} [Thu Mar 14 19:17:53 2019] GET /axf/login/ => generated 1569 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 6/6] 113.87.160.176 () {52 vars in 966 bytes} [Thu Mar 14 19:18:04 2019] POST /axf/login/ => generated 0 bytes in 12 msecs (HTTP/1.1 302) 6 headers in 279 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 7/7] 113.87.160.176 () {46 vars in 862 bytes} [Thu Mar 14 19:18:04 2019] GET /axf/market/ => generated 53229 bytes in 24 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
1f268bbc9822935d33bb7ea15abb8c89 1111111111
1 22222222
[pid: 6917|app: 0|req: 8/8] 113.87.160.176 () {44 vars in 779 bytes} [Thu Mar 14 19:19:10 2019] GET /axf/addcart/?goodsid=502 => generated 162 bytes in 11 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
1f268bbc9822935d33bb7ea15abb8c89 1111111111
1 22222222
[pid: 6917|app: 0|req: 9/9] 113.87.160.176 () {44 vars in 779 bytes} [Thu Mar 14 19:19:14 2019] GET /axf/addcart/?goodsid=501 => generated 129 bytes in 13 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 10/10] 113.87.160.176 () {44 vars in 828 bytes} [Thu Mar 14 19:19:15 2019] GET /axf/cart/ => generated 4019 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 11/11] 113.87.160.176 () {44 vars in 844 bytes} [Thu Mar 14 19:19:17 2019] GET /axf/generateorder/ => generated 1387 bytes in 45 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 12/12] 113.87.160.176 () {44 vars in 776 bytes} [Thu Mar 14 19:19:19 2019] GET /axf/pay/?orderid=11 => generated 1010 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
@@@@@@@@@@@@@@@@@@@@@@@
[pid: 6917|app: 0|req: 13/13] 113.87.160.176 () {42 vars in 740 bytes} [Thu Mar 14 19:19:42 2019] GET /axf/ => generated 20072 bytes in 32 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 6917|app: 0|req: 14/14] 113.87.160.176 () {42 vars in 714 bytes} [Thu Mar 14 19:19:42 2019] GET /favicon.ico => generated 2073 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 15/15] 113.87.160.176 () {44 vars in 801 bytes} [Thu Mar 14 19:19:50 2019] GET /axf/ => generated 20072 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 178 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 16/16] 113.87.160.176 () {44 vars in 821 bytes} [Thu Mar 14 19:19:52 2019] GET /axf/mine/ => generated 6138 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 17/17] 113.87.160.176 () {44 vars in 836 bytes} [Thu Mar 14 19:19:54 2019] GET /axf/orderlist/ => generated 3995 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
[pid: 6917|app: 0|req: 18/18] 113.87.160.176 () {44 vars in 836 bytes} [Thu Mar 14 19:20:13 2019] GET /axf/orderlist/ => generated 3995 bytes in 14 msecs (HTTP/1.1 200) 4 headers in 124 bytes (1 switches on core 0)
